version: "3"

networks:
  net:

services:
  node1:
    container_name: node1
    build: ./src
    image: bsc/client-go:v0.0.1
    working_dir: /opt/ethereum
    environment:
      - NETWORK_ID=13
    volumes:
      - ./data/:/opt/ethereum/
    networks:
      - net

  node2:
    container_name: node2
    image: bsc/client-go:v0.0.1
    working_dir: /opt/ethereum
    environment:
      - NETWORK_ID=13
    volumes:
      - ./data/:/opt/ethereum/
    networks:
      - net
    depends_on:
      - node1
    # ports:
    #   - 7052:7052
